
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 27 04:51:11 EET 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KW_while = 31;
  public static final int NE = 16;
  public static final int LP = 9;
  public static final int LO = 17;
  public static final int RP = 10;
  public static final int ERROR = 22;
  public static final int KW_String = 29;
  public static final int KW_boolean = 28;
  public static final int KW_if = 26;
  public static final int KW_float = 27;
  public static final int ID = 21;
  public static final int AO = 13;
  public static final int FA = 8;
  public static final int ST = 20;
  public static final int DO = 6;
  public static final int LB = 12;
  public static final int LA = 18;
  public static final int RB = 11;
  public static final int MO = 4;
  public static final int PO = 3;
  public static final int EOF = 0;
  public static final int KW_else = 25;
  public static final int SM = 2;
  public static final int KW_return = 30;
  public static final int error = 1;
  public static final int EQ = 15;
  public static final int MD = 14;
  public static final int KW_static = 24;
  public static final int BL = 19;
  public static final int KW_int = 32;
  public static final int NM = 7;
  public static final int TO = 5;
  public static final int KW_class = 23;
}

